-- BILLAR EL BRUJO - V30 - SOLO CANTIDADES DE STOCK DESDE TXT
-- Las cantidades se copian tal cual del TXT y se consideran paquetes.
-- NO cambia precios, categorias, presentaciones ni nombres.

SET @SUCURSAL_ID = 1;
START TRANSACTION;

UPDATE productos SET stock_actual = 9 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('AGUA 2 LITROS')), UPPER(TRIM('AGUA 2L')));
UPDATE productos SET stock_actual = 11 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('AGUA PERSONAL CON GAS')), UPPER(TRIM('AGUA CON GAS')));
UPDATE productos SET stock_actual = 21 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('AGUA PERSONAL SIN GAS')), UPPER(TRIM('AGUA SIN GAS')));
UPDATE productos SET stock_actual = 11 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('AGUA TONICA')));
UPDATE productos SET stock_actual = 13 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('SANTE GRANDE')));
UPDATE productos SET stock_actual = 7 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('SANTE PEQUEÑO')));
UPDATE productos SET stock_actual = 7 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('BLACK')));
UPDATE productos SET stock_actual = 14 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('CICLON')));
UPDATE productos SET stock_actual = 5 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('POWER CHICO')));
UPDATE productos SET stock_actual = 4 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('POWER GRANDE')));
UPDATE productos SET stock_actual = 22 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('RED BULL')));
UPDATE productos SET stock_actual = 4 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('SODA COCA COLA 2 LITROS')), UPPER(TRIM('COCA COLA 2L')));
UPDATE productos SET stock_actual = 5 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('SODA COCA COLA 3 LITROS')), UPPER(TRIM('COCA COLA 3L')));
UPDATE productos SET stock_actual = 12 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('SODA FANTA 2 LITROS')), UPPER(TRIM('FANTA 2L')));
UPDATE productos SET stock_actual = 36 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('SODA PEQUE COCA COLA VARIOS')), UPPER(TRIM('PEQUE')));
UPDATE productos SET stock_actual = 15 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('SODA SPRITE 2 LITROS')), UPPER(TRIM('SPRITE 2L')));
UPDATE productos SET stock_actual = 5 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('COCA AMAIRE N')));
UPDATE productos SET stock_actual = 15 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('COCA EL BRUJO BICO STEVIA')), UPPER(TRIM('COCA BICO ESTEBIA')));
UPDATE productos SET stock_actual = 9 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('COCA EL BRUJO MARACUYA')), UPPER(TRIM('COCA MARACUYA')));
UPDATE productos SET stock_actual = 15 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('COCA EL BRUJO MEDUSA')), UPPER(TRIM('COCA MEDUSA')));
UPDATE productos SET stock_actual = 28 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('COCA MEDUSA N')));
UPDATE productos SET stock_actual = 8 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('COCA EL BRUJO RED BULL')), UPPER(TRIM('COCA REDBUL')));
UPDATE productos SET stock_actual = 3 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('COCA EL BRUJO SANDIA RED BULL')), UPPER(TRIM('COCA SANDIA REDBUL')));
UPDATE productos SET stock_actual = 8 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('COCA EL BRUJO YOGUBOLL')), UPPER(TRIM('COCA YOGUBOL')));
UPDATE productos SET stock_actual = 4 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('COCA YOGUBOL N')));
UPDATE productos SET stock_actual = 8 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('COCA EL BRUJO YOGOURT RED BULL')), UPPER(TRIM('COCA YOGURT REDBUL')));
UPDATE productos SET stock_actual = 10 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('CIGARRO BOHEN BLACK')), UPPER(TRIM('BOHEM BLACK')));
UPDATE productos SET stock_actual = 16 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('CIGARRO BOHEN SANDIA')), UPPER(TRIM('BOHEM SANDIA')));
UPDATE productos SET stock_actual = 0 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('CIGARRO BOHEN YOGOURT')), UPPER(TRIM('BOHEM YOGURT')));
UPDATE productos SET stock_actual = 9 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('CIGARRO CAMEL ACTIVA UNID')), UPPER(TRIM('CAMEL ACTIVA')));
UPDATE productos SET stock_actual = 1 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('CIGARRO CAMEL ATIVO CHICO')), UPPER(TRIM('CAMEL CHICO ACTIVA')));
UPDATE productos SET stock_actual = 43 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('CIGARRO CAMEL SANDIA CHICO')), UPPER(TRIM('CAMEL CHICO SANDIA')));
UPDATE productos SET stock_actual = 13 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('CIGARRO CAMEL SANDIA GRANDE')), UPPER(TRIM('CAMEL SANDIA')));
UPDATE productos SET stock_actual = 10 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('CIGARRO HILS')), UPPER(TRIM('HILLS')));
UPDATE productos SET stock_actual = 10 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('CIGARRO HILLS SANDI')), UPPER(TRIM('HILLS SANDIA')));
UPDATE productos SET stock_actual = 1 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('CERVEZA AMSTEL')));
UPDATE productos SET stock_actual = 16 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('CERVEZA CORONA')));
UPDATE productos SET stock_actual = 44 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('CERVEZA SKUL')), UPPER(TRIM('CERVEZA SKOL')));
UPDATE productos SET stock_actual = 1 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('AMARULA')));
UPDATE productos SET stock_actual = 2 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('FERNET')));
UPDATE productos SET stock_actual = 15 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('RON FLOR DE CAÑA')), UPPER(TRIM('FLOR DE CAÑA')));
UPDATE productos SET stock_actual = 22 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('FLOW ACHACHAIRU')));
UPDATE productos SET stock_actual = 12 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('FLOW CHUFLAY')));
UPDATE productos SET stock_actual = 12 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('FLOW NENE')));
UPDATE productos SET stock_actual = 17 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('FOUR LOCO')));
UPDATE productos SET stock_actual = 2 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('GIN ROSADO')), UPPER(TRIM('GIN')));
UPDATE productos SET stock_actual = 3 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('RON HABANA 7 AÑOS')), UPPER(TRIM('HAVANA')));
UPDATE productos SET stock_actual = 20 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('ICE 51')));
UPDATE productos SET stock_actual = 1 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('NOCHE ICE')));
UPDATE productos SET stock_actual = 0 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('RON DE COCO OLD')), UPPER(TRIM('OLD')));
UPDATE productos SET stock_actual = 2 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('RON ABUELO')), UPPER(TRIM('ABUELO')));
UPDATE productos SET stock_actual = 2 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('TEQUILA JOSE CUERVO')), UPPER(TRIM('TEQUILA')));
UPDATE productos SET stock_actual = 4 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('VINO BLANCO')));
UPDATE productos SET stock_actual = 14 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('VINO TINTO')));
UPDATE productos SET stock_actual = 1 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('QUISQUE BLACK LABEL')), UPPER(TRIM('WHIKY BLACK LABEL')));
UPDATE productos SET stock_actual = 2 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('COMBO FERNET')));
UPDATE productos SET stock_actual = 3 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('COMBO FLOR DE CAÑA')));
UPDATE productos SET stock_actual = 2 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('COMBO RON ABUELO')));
UPDATE productos SET stock_actual = 10 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('VASO CHUFLAY')));
UPDATE productos SET stock_actual = 10 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('VASO FERNET')));
UPDATE productos SET stock_actual = 10 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('VASO FLOR DE CAÑA')));
UPDATE productos SET stock_actual = 10 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('VASO RUM/RON ABUELO')));
UPDATE productos SET stock_actual = 10 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('VASO TEQUILA')));
UPDATE productos SET stock_actual = 10 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('VASO VINO')));
UPDATE productos SET stock_actual = 10 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('VASO VINO tinto')));
UPDATE productos SET stock_actual = 10 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('VASO WHISKY')));
UPDATE productos SET stock_actual = 0 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('NACHO LIMON')));
UPDATE productos SET stock_actual = 8 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('NACHO NORMAL')));
UPDATE productos SET stock_actual = 7 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('NACHOS PICANTES')), UPPER(TRIM('NACHO PICANTE')));
UPDATE productos SET stock_actual = 10 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('NACHO MAX QUESO')), UPPER(TRIM('NACHO SABOR QUESO')));
UPDATE productos SET stock_actual = 13 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('PAPA CHURRAZCO')));
UPDATE productos SET stock_actual = 4 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('PAPA NAX')), UPPER(TRIM('PAPA NAX NORMALES')));
UPDATE productos SET stock_actual = 4 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('PIZONES CHOCOLATE')), UPPER(TRIM('PINZONES CHOCOLATE')));
UPDATE productos SET stock_actual = 9 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('PIZONES PICANTES')), UPPER(TRIM('PIZONES PICANTE')));
UPDATE productos SET stock_actual = 5 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('PLATANITO CHIPS')), UPPER(TRIM('PLATANITO')));
UPDATE productos SET stock_actual = 0 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('TAKIS')));
UPDATE productos SET stock_actual = 0 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('ARCOR')));
UPDATE productos SET stock_actual = 0 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('BELDEN')));
UPDATE productos SET stock_actual = 44 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('CHICLE')));
UPDATE productos SET stock_actual = 11 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('CHICLE GRANDE')));
UPDATE productos SET stock_actual = 10 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('CHICLE PEQUEÑO')));
UPDATE productos SET stock_actual = 0 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('CHUPETE')));
UPDATE productos SET stock_actual = 73 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('CLORETS')));
UPDATE productos SET stock_actual = 14 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('COCA EL BRUJO CHICLE')), UPPER(TRIM('COCA CHICLE')));
UPDATE productos SET stock_actual = 4 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('COCA CHICLE N')));
UPDATE productos SET stock_actual = 12 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('PASTILLAS EUCALIPTO')), UPPER(TRIM('EUCALIPTO')));
UPDATE productos SET stock_actual = 24 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('GROSSO')), UPPER(TRIM('GROSO')));
UPDATE productos SET stock_actual = 10 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('HALLS')));
UPDATE productos SET stock_actual = 0 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('MABEL')));
UPDATE productos SET stock_actual = 6 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('PASTILLAS MINT')), UPPER(TRIM('MINT')));
UPDATE productos SET stock_actual = 4 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('DOCILE MINTY')), UPPER(TRIM('MINTY')));
UPDATE productos SET stock_actual = 2 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('ALIKAL')));
UPDATE productos SET stock_actual = 15 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('COPAS DE VINO')), UPPER(TRIM('COPA')));
UPDATE productos SET stock_actual = 14 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('MESAS')));
UPDATE productos SET stock_actual = 30 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('SILLAS')));
UPDATE productos SET stock_actual = 10 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('VASO DE WISKIE')), UPPER(TRIM('VASOS DE WISKI')));
UPDATE productos SET stock_actual = 4 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('VASO TEQUILERO')), UPPER(TRIM('VASOS TEQUILERO')));
UPDATE productos SET stock_actual = 86 WHERE sucursal_id = @SUCURSAL_ID AND estado = 'ACTIVO' AND UPPER(TRIM(nombre)) IN (UPPER(TRIM('VICO')));

COMMIT;

-- Verificacion:
SELECT nombre, stock_actual FROM productos WHERE sucursal_id = @SUCURSAL_ID AND estado='ACTIVO' ORDER BY nombre;