CREATE TABLE IF NOT EXISTS cierres_turno (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    sucursal_id INT NOT NULL,
    sucursal VARCHAR(120) NOT NULL,
    cajero_usuario VARCHAR(100) NOT NULL,
    cajero_nombre VARCHAR(150) NOT NULL,
    caja VARCHAR(100) NULL,
    turno VARCHAR(30) NOT NULL,
    inicio DATETIME NOT NULL,
    fin DATETIME NOT NULL,
    hora_entrada DATETIME NOT NULL,
    fecha_cierre DATETIME NOT NULL,
    transacciones_total INT NOT NULL DEFAULT 0,
    transacciones_efectivo INT NOT NULL DEFAULT 0,
    transacciones_qr INT NOT NULL DEFAULT 0,
    transacciones_tarjeta INT NOT NULL DEFAULT 0,
    transacciones_transferencia INT NOT NULL DEFAULT 0,
    efectivo DECIMAL(12,2) NOT NULL DEFAULT 0,
    qr DECIMAL(12,2) NOT NULL DEFAULT 0,
    tarjeta DECIMAL(12,2) NOT NULL DEFAULT 0,
    transferencia DECIMAL(12,2) NOT NULL DEFAULT 0,
    sin_metodo DECIMAL(12,2) NOT NULL DEFAULT 0,
    productos_total DECIMAL(12,2) NOT NULL DEFAULT 0,
    mesas_total DECIMAL(12,2) NOT NULL DEFAULT 0,
    minutos_jugados INT NOT NULL DEFAULT 0,
    propinas_total DECIMAL(12,2) NOT NULL DEFAULT 0,
    cortesias_valor DECIMAL(12,2) NOT NULL DEFAULT 0,
    comisiones_total DECIMAL(12,2) NOT NULL DEFAULT 0,
    gastos_total DECIMAL(12,2) NOT NULL DEFAULT 0,
    perdidas_total DECIMAL(12,2) NOT NULL DEFAULT 0,
    total_generado DECIMAL(12,2) NOT NULL DEFAULT 0,
    neto_turno DECIMAL(12,2) NOT NULL DEFAULT 0,
    observaciones TEXT NULL,
    detalle_json LONGTEXT NOT NULL,
    sync_key VARCHAR(220) NOT NULL,
    UNIQUE KEY uk_cierre_turno_sync (sync_key),
    INDEX idx_cierre_turno_fecha (fecha_cierre),
    INDEX idx_cierre_turno_sucursal (sucursal_id),
    INDEX idx_cierre_turno_cajero (cajero_usuario)
);
